name: Bug :bug:
description: Report a bug.
title: "[BUG]: "
labels: []

body:
- type: textarea
  attributes:
    label: Description
    description: Define what part of the repo contains the bug, why this is a bug and any other relevant information.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behaviour 😀
    description: What should happen,
  validations:
    required: true
- type: textarea
  attributes:
    label: Current behaviour 😓
    description: What is happening.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Provide links, steps or code.
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Fix
    description: his can be filled later if not known.
- type: markdown
  attributes:
    value: |
      Thanks for completing our form!
      Don't forget to select the project on the right ->
      and to then, if possible, fill in the project fields.

