name: Doc or Lib Update 📌
description: Track a Documentation or Library/SDK update that is required
type: "Subtask"
projects: ["Woosmap/29"]

body:
- type: dropdown
  attributes:
    label: Is this a Doc or Lib/SDK change
    options:
      - Doc
      - Lib/SDK
  validations:
    required: true
- type: input
  attributes:
    label: Related Issue
    Description: URL to the issue which causes this change
- type: textarea
  attributes:
    label: Description
    description: List and Explain exactly what documentation or Library change is required
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Thanks for completing the form!
      Don't forget to fill in the project fields.
