name: Feature 📗
description: Track a single simple piece of work
labels: []
projects: ["Woosmap/29"]

body:
- type: markdown
  attributes:
    value: |
      For more info on how to use a Task look [here](https://docs.woosmap.dev/how_we_work/issues/#tasks)
- type: textarea
  attributes:
    label: What?
    description: Detailed description of the task.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why?
    description: Why is this change important.
  validations:
    required: true
- type: textarea
  attributes:
    label: Documentation?
    description: Are there any internal or public documentation updates that should come with this change.
  validations:
    required: true
- type: textarea
  attributes:
    label: Engineering Section
    description: After engineers have discussed are there any comments, solution points or push back
- type: textarea
  attributes:
    label: Blockers
    description: List tasks, info etc., if any, which must be completed to start this one.
    placeholder: |
      "- [ ] <Woosmap/maps#1>"
- type: markdown
  attributes:
    value: |
      Thanks for completing the form!
      Don't forget to fill in the project fields.
